spring:
  cloud:
    nacos:
      discovery:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
      config:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
    sentinel:
      transport:
        # port: 9002 # 应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer,可不提供，默认为 8719，若端口冲突会自动向下探测可用的端口。
        dashboard: 127.0.0.1:8849 # Sentinel 控制台地址
      datasource: # 动态数据源支持
        ds1: # ds1, ds2, ds3, ds4 是ReadableDataSource的名字，可随意编写。后面的 file ，zk ，nacos , apollo 就是对应具体的数据源，它们后面的配置就是这些具体数据源各自的配置。
          nacos:
            namespace: ${spring.cloud.nacos.discovery.namespace}
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
#    password: redis123 # Redis服务器连接密码（默认为空）
    timeout: 10000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 35 # 连接池中的最大空闲连接 默认 8
        min-idle: 5 # 连接池中的最小空闲连接 默认 0
